/* generated by Svelte v3.37.0 */
import {
	SvelteComponent,
	detach,
	element,
	init,
	insert,
	noop,
	safe_not_equal
} from "/db/my-app/node_modules/svelte/internal/index.mjs";

function create_fragment(ctx) {
	let button;

	return {
		c() {
			button = element("button");
			button.textContent = "Test me";
		},
		m(target, anchor) {
			insert(target, button, anchor);
		},
		p: noop,
		i: noop,
		o: noop,
		d(detaching) {
			if (detaching) detach(button);
		}
	};
}

class Component extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, null, create_fragment, safe_not_equal, {});
	}
}

export default Component;