/* generated by Svelte v3.37.0 */
import {
	SvelteComponent,
	append,
	attr,
	binding_callbacks,
	detach,
	element,
	init,
	insert,
	noop,
	safe_not_equal
} from "/~/node_modules/svelte/internal/index.mjs";

import { onMount } from "/~/node_modules/svelte/index.mjs";
import "https://unpkg.com/d3@7.0.0";

function add_css() {
	var style = element("style");
	style.id = "svelte-16mgb46-style";
	style.textContent = ".chart.svelte-16mgb46 div{font:10px sans-serif;background-color:steelblue;text-align:right;padding:3px;margin:1px;color:white}";
	append(document.head, style);
}

function create_fragment(ctx) {
	let div;

	return {
		c() {
			div = element("div");
			attr(div, "class", "chart svelte-16mgb46");
		},
		m(target, anchor) {
			insert(target, div, anchor);
			/*div_binding*/ ctx[1](div);
		},
		p: noop,
		i: noop,
		o: noop,
		d(detaching) {
			if (detaching) detach(div);
			/*div_binding*/ ctx[1](null);
		}
	};
}

function instance($$self, $$props, $$invalidate) {
	var data = [30, 86, 168, 281, 303, 365];
	let el;

	onMount(() => {
		d3.select(el).selectAll("div").data(data).enter().append("div").style("width", function (d) {
			return d + "px";
		}).text(function (d) {
			return d;
		});
	});

	function div_binding($$value) {
		binding_callbacks[$$value ? "unshift" : "push"](() => {
			el = $$value;
			$$invalidate(0, el);
		});
	}

	return [el, div_binding];
}

class Component extends SvelteComponent {
	constructor(options) {
		super();
		if (!document.getElementById("svelte-16mgb46-style")) add_css();
		init(this, options, instance, create_fragment, safe_not_equal, {});
	}
}

export default Component;