services:
    reverse-proxy:
        image: nginx
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        ports:
            - 80:80
    postgres:
        image: postgres:10
        environment:
            POSTGRES_DB: guillotina
            POSTGRES_USER: guillotina
            POSTGRES_PASSWORD: guillotina
    abfab:
        build:
            context: ../guillotina/abfab
            dockerfile: Dockerfile
        command: sh -c "sleep 5 && guillotina"
        ports:
            - 8080:8080
        links:
            - postgres
    init:
        build:
            context: ..
            dockerfile: docker/Dockerfile-init
        command: sh init.sh
        links:
            - postgres
            - abfab
