/* generated by Svelte v3.37.0 */
import {
	SvelteComponent,
	append,
	attr,
	check_outros,
	create_component,
	destroy_component,
	detach,
	element,
	group_outros,
	init,
	insert,
	mount_component,
	safe_not_equal,
	space,
	transition_in,
	transition_out
} from "/db/my-app/node_modules/svelte/internal/index.mjs";

import VimEditor from "./vim.svelte";
import Viewer from "./viewer.svelte";
import AFButton from "../ui/button.svelte";

function add_css() {
	var style = element("style");
	style.id = "svelte-1qcgxxn-style";
	style.textContent = "header.svelte-1qcgxxn.svelte-1qcgxxn{height:2em;display:flex;align-items:center}header.svelte-1qcgxxn img.svelte-1qcgxxn{height:2em;padding:0.2em;margin-left:0.2em}main.svelte-1qcgxxn.svelte-1qcgxxn{display:flex}nav.svelte-1qcgxxn.svelte-1qcgxxn{width:3em}ul.svelte-1qcgxxn.svelte-1qcgxxn{list-style-type:none;margin:0;padding:0;text-align:center}nav.svelte-1qcgxxn li.svelte-1qcgxxn{padding:1em 0}.editor-container.svelte-1qcgxxn.svelte-1qcgxxn{display:flex;flex-direction:column;align-items:center;height:calc(100vh - 2.5em);width:calc(100vw - 3.5em);margin:0px;padding:0px;overflow:hidden}.editor-container.half.svelte-1qcgxxn.svelte-1qcgxxn{width:calc(50vw - 3.5em)}";
	append(document.head, style);
}

// (84:4) {#if play}
function create_if_block(ctx) {
	let viewer;
	let current;

	viewer = new Viewer({
			props: { componentPath: /*componentPath*/ ctx[2] }
		});

	return {
		c() {
			create_component(viewer.$$.fragment);
		},
		m(target, anchor) {
			mount_component(viewer, target, anchor);
			current = true;
		},
		p(ctx, dirty) {
			const viewer_changes = {};
			if (dirty & /*componentPath*/ 4) viewer_changes.componentPath = /*componentPath*/ ctx[2];
			viewer.$set(viewer_changes);
		},
		i(local) {
			if (current) return;
			transition_in(viewer.$$.fragment, local);
			current = true;
		},
		o(local) {
			transition_out(viewer.$$.fragment, local);
			current = false;
		},
		d(detaching) {
			destroy_component(viewer, detaching);
		}
	};
}

function create_fragment(ctx) {
	let link;
	let t0;
	let header;
	let img;
	let img_src_value;
	let t1;
	let ul0;
	let li0;
	let afbutton0;
	let t2;
	let main;
	let nav;
	let ul1;
	let li1;
	let afbutton1;
	let t3;
	let li2;
	let afbutton2;
	let t4;
	let li3;
	let afbutton3;
	let t5;
	let div;
	let vimeditor;
	let div_class_value;
	let t6;
	let current;

	afbutton0 = new AFButton({
			props: {
				kind: "primary",
				aspect: "basic",
				icon: "play",
				label: "Play",
				size: "small",
				active: /*play*/ ctx[1]
			}
		});

	afbutton0.$on("click", /*togglePlay*/ ctx[3]);

	afbutton1 = new AFButton({
			props: {
				kind: "primary",
				aspect: "basic",
				icon: "components",
				label: "Components",
				size: "small",
				active: true
			}
		});

	afbutton2 = new AFButton({
			props: {
				kind: "primary",
				aspect: "basic",
				icon: "data",
				label: "Data",
				size: "small"
			}
		});

	afbutton3 = new AFButton({
			props: {
				kind: "primary",
				aspect: "basic",
				icon: "libraries",
				label: "Libraries",
				size: "small"
			}
		});

	vimeditor = new VimEditor({ props: { context: /*context*/ ctx[0] } });
	let if_block = /*play*/ ctx[1] && create_if_block(ctx);

	return {
		c() {
			link = element("link");
			t0 = space();
			header = element("header");
			img = element("img");
			t1 = space();
			ul0 = element("ul");
			li0 = element("li");
			create_component(afbutton0.$$.fragment);
			t2 = space();
			main = element("main");
			nav = element("nav");
			ul1 = element("ul");
			li1 = element("li");
			create_component(afbutton1.$$.fragment);
			t3 = space();
			li2 = element("li");
			create_component(afbutton2.$$.fragment);
			t4 = space();
			li3 = element("li");
			create_component(afbutton3.$$.fragment);
			t5 = space();
			div = element("div");
			create_component(vimeditor.$$.fragment);
			t6 = space();
			if (if_block) if_block.c();
			attr(link, "rel", "stylesheet");
			attr(link, "href", "/db/my-app/abfab/pastanaga/styles.a2374b02e1a26e40320b.css");
			if (img.src !== (img_src_value = "/db/my-app/abfab/abfab.svg")) attr(img, "src", img_src_value);
			attr(img, "alt", "AbFab logo");
			attr(img, "class", "svelte-1qcgxxn");
			attr(ul0, "class", "svelte-1qcgxxn");
			attr(header, "class", "svelte-1qcgxxn");
			attr(li1, "class", "svelte-1qcgxxn");
			attr(li2, "class", "svelte-1qcgxxn");
			attr(li3, "class", "svelte-1qcgxxn");
			attr(ul1, "class", "svelte-1qcgxxn");
			attr(nav, "class", "svelte-1qcgxxn");
			attr(div, "class", div_class_value = "editor-container " + (/*play*/ ctx[1] ? "half" : "") + " svelte-1qcgxxn");
			attr(main, "class", "svelte-1qcgxxn");
		},
		m(target, anchor) {
			append(document.head, link);
			insert(target, t0, anchor);
			insert(target, header, anchor);
			append(header, img);
			append(header, t1);
			append(header, ul0);
			append(ul0, li0);
			mount_component(afbutton0, li0, null);
			insert(target, t2, anchor);
			insert(target, main, anchor);
			append(main, nav);
			append(nav, ul1);
			append(ul1, li1);
			mount_component(afbutton1, li1, null);
			append(ul1, t3);
			append(ul1, li2);
			mount_component(afbutton2, li2, null);
			append(ul1, t4);
			append(ul1, li3);
			mount_component(afbutton3, li3, null);
			append(main, t5);
			append(main, div);
			mount_component(vimeditor, div, null);
			append(main, t6);
			if (if_block) if_block.m(main, null);
			current = true;
		},
		p(ctx, [dirty]) {
			const afbutton0_changes = {};
			if (dirty & /*play*/ 2) afbutton0_changes.active = /*play*/ ctx[1];
			afbutton0.$set(afbutton0_changes);
			const vimeditor_changes = {};
			if (dirty & /*context*/ 1) vimeditor_changes.context = /*context*/ ctx[0];
			vimeditor.$set(vimeditor_changes);

			if (!current || dirty & /*play*/ 2 && div_class_value !== (div_class_value = "editor-container " + (/*play*/ ctx[1] ? "half" : "") + " svelte-1qcgxxn")) {
				attr(div, "class", div_class_value);
			}

			if (/*play*/ ctx[1]) {
				if (if_block) {
					if_block.p(ctx, dirty);

					if (dirty & /*play*/ 2) {
						transition_in(if_block, 1);
					}
				} else {
					if_block = create_if_block(ctx);
					if_block.c();
					transition_in(if_block, 1);
					if_block.m(main, null);
				}
			} else if (if_block) {
				group_outros();

				transition_out(if_block, 1, 1, () => {
					if_block = null;
				});

				check_outros();
			}
		},
		i(local) {
			if (current) return;
			transition_in(afbutton0.$$.fragment, local);
			transition_in(afbutton1.$$.fragment, local);
			transition_in(afbutton2.$$.fragment, local);
			transition_in(afbutton3.$$.fragment, local);
			transition_in(vimeditor.$$.fragment, local);
			transition_in(if_block);
			current = true;
		},
		o(local) {
			transition_out(afbutton0.$$.fragment, local);
			transition_out(afbutton1.$$.fragment, local);
			transition_out(afbutton2.$$.fragment, local);
			transition_out(afbutton3.$$.fragment, local);
			transition_out(vimeditor.$$.fragment, local);
			transition_out(if_block);
			current = false;
		},
		d(detaching) {
			detach(link);
			if (detaching) detach(t0);
			if (detaching) detach(header);
			destroy_component(afbutton0);
			if (detaching) detach(t2);
			if (detaching) detach(main);
			destroy_component(afbutton1);
			destroy_component(afbutton2);
			destroy_component(afbutton3);
			destroy_component(vimeditor);
			if (if_block) if_block.d();
		}
	};
}

function instance($$self, $$props, $$invalidate) {
	let { context } = $$props;
	let play = false;
	let componentPath;

	function togglePlay() {
		$$invalidate(2, componentPath = location.pathname.replace("/@edit", ""));
		$$invalidate(1, play = !play);
		window.dispatchEvent(new Event("resize"));
	}

	$$self.$$set = $$props => {
		if ("context" in $$props) $$invalidate(0, context = $$props.context);
	};

	return [context, play, componentPath, togglePlay];
}

class Component extends SvelteComponent {
	constructor(options) {
		super();
		if (!document.getElementById("svelte-1qcgxxn-style")) add_css();
		init(this, options, instance, create_fragment, safe_not_equal, { context: 0 });
	}
}

export default Component;