/* generated by Svelte v3.37.0 */
import {
	SvelteComponent,
	append,
	attr,
	check_outros,
	create_component,
	destroy_component,
	destroy_each,
	detach,
	element,
	empty,
	group_outros,
	init,
	insert,
	listen,
	mount_component,
	noop,
	safe_not_equal,
	set_data,
	space,
	text,
	toggle_class,
	transition_in,
	transition_out
} from "/~/libs/svelte/internal/index.mjs";

import { getTreeItem, updateTreeItem } from "./editor.js";
import AFIcon from "/~/abfab/ui/icon.svelte";

function get_each_context(ctx, list, i) {
	const child_ctx = ctx.slice();
	child_ctx[0] = list[i];
	return child_ctx;
}

// (20:0) {:else}
function create_else_block(ctx) {
	let aficon;
	let current;
	aficon = new AFIcon({ props: { size: "small", icon: "file" } });
	aficon.$on("click", /*toggle*/ ctx[1]);

	return {
		c() {
			create_component(aficon.$$.fragment);
		},
		m(target, anchor) {
			mount_component(aficon, target, anchor);
			current = true;
		},
		p: noop,
		i(local) {
			if (current) return;
			transition_in(aficon.$$.fragment, local);
			current = true;
		},
		o(local) {
			transition_out(aficon.$$.fragment, local);
			current = false;
		},
		d(detaching) {
			destroy_component(aficon, detaching);
		}
	};
}

// (18:0) {#if item.type === 'Directory' }
function create_if_block_1(ctx) {
	let aficon;
	let current;

	aficon = new AFIcon({
			props: {
				size: "small",
				icon: /*item*/ ctx[0].expanded
				? "chevron-down"
				: "chevron-right"
			}
		});

	aficon.$on("click", /*toggle*/ ctx[1]);

	return {
		c() {
			create_component(aficon.$$.fragment);
		},
		m(target, anchor) {
			mount_component(aficon, target, anchor);
			current = true;
		},
		p(ctx, dirty) {
			const aficon_changes = {};

			if (dirty & /*item*/ 1) aficon_changes.icon = /*item*/ ctx[0].expanded
			? "chevron-down"
			: "chevron-right";

			aficon.$set(aficon_changes);
		},
		i(local) {
			if (current) return;
			transition_in(aficon.$$.fragment, local);
			current = true;
		},
		o(local) {
			transition_out(aficon.$$.fragment, local);
			current = false;
		},
		d(detaching) {
			destroy_component(aficon, detaching);
		}
	};
}

// (24:0) {#if item.children && item.expanded }
function create_if_block(ctx) {
	let ul;
	let current;
	let each_value = /*item*/ ctx[0].children;
	let each_blocks = [];

	for (let i = 0; i < each_value.length; i += 1) {
		each_blocks[i] = create_each_block(get_each_context(ctx, each_value, i));
	}

	const out = i => transition_out(each_blocks[i], 1, 1, () => {
		each_blocks[i] = null;
	});

	return {
		c() {
			ul = element("ul");

			for (let i = 0; i < each_blocks.length; i += 1) {
				each_blocks[i].c();
			}
		},
		m(target, anchor) {
			insert(target, ul, anchor);

			for (let i = 0; i < each_blocks.length; i += 1) {
				each_blocks[i].m(ul, null);
			}

			current = true;
		},
		p(ctx, dirty) {
			if (dirty & /*item*/ 1) {
				each_value = /*item*/ ctx[0].children;
				let i;

				for (i = 0; i < each_value.length; i += 1) {
					const child_ctx = get_each_context(ctx, each_value, i);

					if (each_blocks[i]) {
						each_blocks[i].p(child_ctx, dirty);
						transition_in(each_blocks[i], 1);
					} else {
						each_blocks[i] = create_each_block(child_ctx);
						each_blocks[i].c();
						transition_in(each_blocks[i], 1);
						each_blocks[i].m(ul, null);
					}
				}

				group_outros();

				for (i = each_value.length; i < each_blocks.length; i += 1) {
					out(i);
				}

				check_outros();
			}
		},
		i(local) {
			if (current) return;

			for (let i = 0; i < each_value.length; i += 1) {
				transition_in(each_blocks[i]);
			}

			current = true;
		},
		o(local) {
			each_blocks = each_blocks.filter(Boolean);

			for (let i = 0; i < each_blocks.length; i += 1) {
				transition_out(each_blocks[i]);
			}

			current = false;
		},
		d(detaching) {
			if (detaching) detach(ul);
			destroy_each(each_blocks, detaching);
		}
	};
}

// (26:4) {#each item.children as item}
function create_each_block(ctx) {
	let li;
	let component;
	let current;
	component = new Component({ props: { item: /*item*/ ctx[0] } });

	return {
		c() {
			li = element("li");
			create_component(component.$$.fragment);
		},
		m(target, anchor) {
			insert(target, li, anchor);
			mount_component(component, li, null);
			current = true;
		},
		p(ctx, dirty) {
			const component_changes = {};
			if (dirty & /*item*/ 1) component_changes.item = /*item*/ ctx[0];
			component.$set(component_changes);
		},
		i(local) {
			if (current) return;
			transition_in(component.$$.fragment, local);
			current = true;
		},
		o(local) {
			transition_out(component.$$.fragment, local);
			current = false;
		},
		d(detaching) {
			if (detaching) detach(li);
			destroy_component(component);
		}
	};
}

function create_fragment(ctx) {
	let current_block_type_index;
	let if_block0;
	let t0;
	let a;
	let t1_value = /*item*/ ctx[0].name + "";
	let t1;
	let a_href_value;
	let t2;
	let if_block1_anchor;
	let current;
	let mounted;
	let dispose;
	const if_block_creators = [create_if_block_1, create_else_block];
	const if_blocks = [];

	function select_block_type(ctx, dirty) {
		if (/*item*/ ctx[0].type === "Directory") return 0;
		return 1;
	}

	current_block_type_index = select_block_type(ctx, -1);
	if_block0 = if_blocks[current_block_type_index] = if_block_creators[current_block_type_index](ctx);
	let if_block1 = /*item*/ ctx[0].children && /*item*/ ctx[0].expanded && create_if_block(ctx);

	return {
		c() {
			if_block0.c();
			t0 = space();
			a = element("a");
			t1 = text(t1_value);
			t2 = space();
			if (if_block1) if_block1.c();
			if_block1_anchor = empty();
			attr(a, "href", a_href_value = `${/*item*/ ctx[0].path}/@edit`);
			toggle_class(a, "selected", /*item*/ ctx[0].selected);
		},
		m(target, anchor) {
			if_blocks[current_block_type_index].m(target, anchor);
			insert(target, t0, anchor);
			insert(target, a, anchor);
			append(a, t1);
			insert(target, t2, anchor);
			if (if_block1) if_block1.m(target, anchor);
			insert(target, if_block1_anchor, anchor);
			current = true;

			if (!mounted) {
				dispose = listen(a, "click", /*click*/ ctx[2]);
				mounted = true;
			}
		},
		p(ctx, [dirty]) {
			let previous_block_index = current_block_type_index;
			current_block_type_index = select_block_type(ctx, dirty);

			if (current_block_type_index === previous_block_index) {
				if_blocks[current_block_type_index].p(ctx, dirty);
			} else {
				group_outros();

				transition_out(if_blocks[previous_block_index], 1, 1, () => {
					if_blocks[previous_block_index] = null;
				});

				check_outros();
				if_block0 = if_blocks[current_block_type_index];

				if (!if_block0) {
					if_block0 = if_blocks[current_block_type_index] = if_block_creators[current_block_type_index](ctx);
					if_block0.c();
				} else {
					if_block0.p(ctx, dirty);
				}

				transition_in(if_block0, 1);
				if_block0.m(t0.parentNode, t0);
			}

			if ((!current || dirty & /*item*/ 1) && t1_value !== (t1_value = /*item*/ ctx[0].name + "")) set_data(t1, t1_value);

			if (!current || dirty & /*item*/ 1 && a_href_value !== (a_href_value = `${/*item*/ ctx[0].path}/@edit`)) {
				attr(a, "href", a_href_value);
			}

			if (dirty & /*item*/ 1) {
				toggle_class(a, "selected", /*item*/ ctx[0].selected);
			}

			if (/*item*/ ctx[0].children && /*item*/ ctx[0].expanded) {
				if (if_block1) {
					if_block1.p(ctx, dirty);

					if (dirty & /*item*/ 1) {
						transition_in(if_block1, 1);
					}
				} else {
					if_block1 = create_if_block(ctx);
					if_block1.c();
					transition_in(if_block1, 1);
					if_block1.m(if_block1_anchor.parentNode, if_block1_anchor);
				}
			} else if (if_block1) {
				group_outros();

				transition_out(if_block1, 1, 1, () => {
					if_block1 = null;
				});

				check_outros();
			}
		},
		i(local) {
			if (current) return;
			transition_in(if_block0);
			transition_in(if_block1);
			current = true;
		},
		o(local) {
			transition_out(if_block0);
			transition_out(if_block1);
			current = false;
		},
		d(detaching) {
			if_blocks[current_block_type_index].d(detaching);
			if (detaching) detach(t0);
			if (detaching) detach(a);
			if (detaching) detach(t2);
			if (if_block1) if_block1.d(detaching);
			if (detaching) detach(if_block1_anchor);
			mounted = false;
			dispose();
		}
	};
}

function instance($$self, $$props, $$invalidate) {
	let { item } = $$props;

	const toggle = () => {
		updateTreeItem({ ...item, expanded: !item.expanded });
	};

	const click = () => {
		const currentSelected = getTreeItem(window.location.pathname.replace("/@edit", ""));

		if (currentSelected) {
			updateTreeItem({ ...currentSelected, selected: false });
		}

		updateTreeItem({ ...item, selected: true });
	};

	$$self.$$set = $$props => {
		if ("item" in $$props) $$invalidate(0, item = $$props.item);
	};

	return [item, toggle, click];
}

class Component extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, instance, create_fragment, safe_not_equal, { item: 0 });
	}
}

export default Component;